[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt", "python3 -m nltk.downloader vader_lexicon"]

[start]
cmd = "bash entrypoint.sh"
